public class BerryWrapperClass{
    public String name{get;set;}
    public String test{get;set;}
    public String test2{get;set;}
    public String test1{get;set;}
        public String test3{get;set;} 
    public String test4{get;set;}
     public String test6{get;set;}
      public String test7{get;set;}
   public String test8{get;set;}
    public String test81{get;set;}
     public String test82{get;set;}
      public String test83{get;set;}
}